#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Xamarin.ActionSheet.Resource", IsApplication=false)]

namespace Xamarin.ActionSheet
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public static int actionSheetBackground = 2130771969;
			
			// aapt resource value: 0x7f010009
			public static int actionSheetPadding = 2130771977;
			
			// aapt resource value: 0x7f010000
			public static int actionSheetStyle = 2130771968;
			
			// aapt resource value: 0x7f01000c
			public static int actionSheetTextSize = 2130771980;
			
			// aapt resource value: 0x7f010002
			public static int cancelButtonBackground = 2130771970;
			
			// aapt resource value: 0x7f01000b
			public static int cancelButtonMarginTop = 2130771979;
			
			// aapt resource value: 0x7f010007
			public static int cancelButtonTextColor = 2130771975;
			
			// aapt resource value: 0x7f010005
			public static int otherButtonBottomBackground = 2130771973;
			
			// aapt resource value: 0x7f010004
			public static int otherButtonMiddleBackground = 2130771972;
			
			// aapt resource value: 0x7f010006
			public static int otherButtonSingleBackground = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public static int otherButtonSpacing = 2130771978;
			
			// aapt resource value: 0x7f010008
			public static int otherButtonTextColor = 2130771976;
			
			// aapt resource value: 0x7f010003
			public static int otherButtonTopBackground = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int slt_as_ios7_cancel_bt = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int slt_as_ios7_other_bt_bottom = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int slt_as_ios7_other_bt_middle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int slt_as_ios7_other_bt_single = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int slt_as_ios7_other_bt_top = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public static int actionsheet_bg_ios6 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int actionsheet_bottom_normal = 2130903041;
			
			// aapt resource value: 0x7f030002
			public static int actionsheet_bottom_pressed = 2130903042;
			
			// aapt resource value: 0x7f030003
			public static int actionsheet_cancel_bt_bg = 2130903043;
			
			// aapt resource value: 0x7f030004
			public static int actionsheet_middle_normal = 2130903044;
			
			// aapt resource value: 0x7f030005
			public static int actionsheet_middle_pressed = 2130903045;
			
			// aapt resource value: 0x7f030006
			public static int actionsheet_other_bt_bg = 2130903046;
			
			// aapt resource value: 0x7f030007
			public static int actionsheet_single_normal = 2130903047;
			
			// aapt resource value: 0x7f030008
			public static int actionsheet_single_pressed = 2130903048;
			
			// aapt resource value: 0x7f030009
			public static int actionsheet_top_normal = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public static int actionsheet_top_pressed = 2130903050;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public static int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public static int ActionSheetStyleiOS6 = 2130968576;
			
			// aapt resource value: 0x7f040001
			public static int ActionSheetStyleiOS7 = 2130968577;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ActionSheet = new int[]
			{
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 0
			public static int ActionSheet_actionSheetBackground = 0;
			
			// aapt resource value: 8
			public static int ActionSheet_actionSheetPadding = 8;
			
			// aapt resource value: 11
			public static int ActionSheet_actionSheetTextSize = 11;
			
			// aapt resource value: 1
			public static int ActionSheet_cancelButtonBackground = 1;
			
			// aapt resource value: 10
			public static int ActionSheet_cancelButtonMarginTop = 10;
			
			// aapt resource value: 6
			public static int ActionSheet_cancelButtonTextColor = 6;
			
			// aapt resource value: 4
			public static int ActionSheet_otherButtonBottomBackground = 4;
			
			// aapt resource value: 3
			public static int ActionSheet_otherButtonMiddleBackground = 3;
			
			// aapt resource value: 5
			public static int ActionSheet_otherButtonSingleBackground = 5;
			
			// aapt resource value: 9
			public static int ActionSheet_otherButtonSpacing = 9;
			
			// aapt resource value: 7
			public static int ActionSheet_otherButtonTextColor = 7;
			
			// aapt resource value: 2
			public static int ActionSheet_otherButtonTopBackground = 2;
			
			public static int[] ActionSheets = new int[]
			{
					2130771968};
			
			// aapt resource value: 0
			public static int ActionSheets_actionSheetStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
